### ISSUE TITLE
Does this allow for audio streaming?

### ISSUE THREAD

**Issue by Avis2912** [feedbee/ai-read-it#1]
Thanks for making this! Just curious if this allows for a stream object I can use to minimize response delay

**Comment by valery-leontyev-idt** [comment]
Unfortunately, ChatGPT TTS API does not support streaming. See https://platform.openai.com/docs/api-reference/audio/createSpeech#audio-createspeech-input.

Moreover, it has a limit of 3 requests per minute, so splitting text into a large number of smaller chunks to get faster output is also not a solution.

**Comment by feedbee** [comment]
Unfortunately, ChatGPT TTS API does not support streaming. See https://platform.openai.com/docs/api-reference/audio/createSpeech#audio-createspeech-input.

Moreover, it has a limit of 3 requests per minute, so splitting text into a large number of smaller chunks to get faster output is also not a solution.
